template_path: "vpc.yaml"

parameters:
  AvailabilityZones:
    - "ap-southeast-2a"
    - "ap-southeast-2b"
    - "ap-southeast-2c"
  CreateAdditionalPrivateSubnets: "false"
  CreateNATService: "true"
  EnableVPCFlowLogs: "false"
  VPCFlowLogRetentionInDays: "14"
  CreatePrivateSubnets: "true"
  KeyPairName: ""
  NATInstanceType: "t2.nano"
  NumberOfAZs: "3"
  NumberOfNATGateways: "Across all Public Subnets"
  PrivateSubnet1ACIDR: "10.1.0.0/24"
  PrivateSubnet1BCIDR: "0.0.0.0/21"
  PrivateSubnet2ACIDR: "10.1.1.0/24"
  PrivateSubnet2BCIDR: "0.0.0.0/21"
  PrivateSubnet3ACIDR: "10.1.2.0/24"
  PrivateSubnet3BCIDR: "0.0.0.0/21"
  PrivateSubnet4ACIDR: "0.0.0.0/21"
  PrivateSubnet4BCIDR: "0.0.0.0/21"
  PublicSubnet1CIDR: "10.1.3.0/24"
  PublicSubnet2CIDR: "10.1.4.0/24"
  PublicSubnet3CIDR: "10.1.5.0/24"
  PublicSubnet4CIDR: "0.0.0.0/21"
  VPCCIDR: "10.1.0.0/21"
